notifications:
  email: false

before_install:
  # Install makeindex, if you do not use an index you can remove this (also remove the extra makeindex call).
  - sudo apt-get install texlive-binaries

install:
  # Silent install from conda docs
  # https://conda.io/docs/user-guide/install/macos.html#install-macos-silent
  # adapted using
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html

  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"

  # If not yet installed, obtain Miniconda
  # and tectonic
  # From tectonic docs
  # https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda update --all;
      conda install tectonic;
    fi
  - conda info -a
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic
script: # Change working directory each time so including files will work. Change back so the pdfs can be found for deployment. This way, building multiple files goes well.
 - cd ./src/
 # Tectonic does not include makeindex, so that needs to be done manually.
 - tectonic ./main.tex
 - makeindex ./main.idx
 - tectonic ./main.tex --print
 - cd ../
deploy:
  provider: releases
  file:
  - ./src/main.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
